# Generated by Django 4.2.3 on 2023-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_admin_candidate_election_voter_participated_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='access_type',
            field=models.CharField(choices=[('OPEN_FOR_ALL', 'open_for_all'), ('VIA_URL', 'via_url')], default='open_for_all', max_length=20),
        ),
    ]
