# Generated by Django 4.2.3 on 2023-10-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_election_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='candidates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.candidate'),
        ),
    ]
