# Generated by Django 4.2.3 on 2023-10-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_election_candidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.admin'),
        ),
    ]
