# Generated by Django 4.2.3 on 2023-11-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_remove_candidate_no_of_votes_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='age',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='photo',
        ),
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candiatevotes', to='voting.election'),
        ),
    ]
