# Generated by Django 4.2.3 on 2023-12-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_remove_admin_age_remove_admin_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='participated_in',
        ),
        migrations.AddField(
            model_name='voter',
            name='participated_in',
            field=models.ManyToManyField(blank=True, to='voting.election'),
        ),
    ]
