# Generated by Django 5.1.2 on 2024-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_remove_voter_participated_in_voter_participated_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time_cast',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
